name: Publish Common
on:
  push:
    paths:
    - 'k-common/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish new version to NPM
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        working-directory: ./k-common
        run: yarn install
      - name: Build Dependencies
        working-directory: ./k-common
        run: yarn install
      - name: Publish Package
        working-directory: ./k-common
        run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
